name: GemsEconomy
main: me.xanium.gemseconomy.GemsEconomy
version: 5.0
author: Xanium
description: A multi-currency economy plugin for spigot servers!
website: https://www.spigotmc.org/resources/gemseconomy.19655/
load: STARTUP
loadbefore:
  - ItemFrameShops
softdepend: [Vault]
commands:
  gbalance:
    description: Shows your balances
    usage: /gbalance (account)
    aliases: [gbal, gmoney, bal]
  gbaltop:
    description: Shows the top balances of the server
    usage: /gbaltop (currency) (page)
    aliases: [gmoneytop, gecotop, gtop, gbaltop]
  gcurrency:
    description: Manage the currencies.
    usage: /gcurrencies
    aliases: [gcurr, gemscurrencies, gcurrency, currencies]
  geconomy:
    description: Give, set or take currency.
    usage: /geco <set|take|give> <account> <amount> (currency)
    aliases: [geconomy, geco, gemseconomy]
  gpay:
    description: Pays another account
    usage: /pay <account> <amount> (currency)
    aliases: [gpay, gemspay]
  gcheque:
    usage: /cheque
    description: Write or Redeem a cheque.
    aliases: [note, banknote]
  gexchange:
    usage: /gexchange
    description: Exchange currencies.
    aliases: [gex, gemsexchange, gexchange]